# These are supported funding model platforms

github: [Pomax]
patreon: bezierinfo
custom: [https://pomax.github.io/bezierinfo/#:~:text=software%2C%20please%20consider-,donating,-(any%20amount%20helps]
